# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2c94d3b68495931febfe7c4b04038f511be1532ef76f35826b6b9c9516dee5b85e8f0f03bad4b9feff553bb3d2745d54419958853b68222d565cd9872594a4e

test:
  secret_key_base: 7134a55499c620c6f794f6525af249f7737afed616b97238e469240839bf8a3d4e054864b29422810da8c4a9b93ccfbbebc816c68b09ac7b0c004b6fa7ab7a1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
